"use server";
import { randomBytes,createHash } from "node:crypto";
import { officeContext,recordOfficeAction } from "@/lib/office/context";
import { officeAction,formText } from "@/lib/office/action";
import { canSubscribe,googleAccessToken,googleRequest,syncGoogleCalendar } from "@/lib/calendar/integrations";
import { SITE_URL } from "@/lib/org";
import type { ActionState } from "@/app/(public)/actions";
export async function createSubscription(_:ActionState,form:FormData){return officeAction(async()=>{const {db,org,user,profile}=await officeContext();const target=formText(form,'profile_id',40)||profile.id;if(!await canSubscribe(user.id,org,target))throw new Error('Your role cannot subscribe to this calendar.');const token=randomBytes(32).toString('base64url');const {error}=await db.from('calendar_subscriptions').insert({organization_id:org,user_id:user.id,calendar_profile_id:target,token_hash:createHash('sha256').update(token).digest('hex')});if(error)throw error;return `${SITE_URL}/api/calendar/pastoral/${token}`;});}
export async function revokeSubscriptions(_:ActionState,form:FormData){return officeAction(async()=>{const {db,org,user,profile}=await officeContext();const {error}=await db.from('calendar_subscriptions').update({revoked_at:new Date().toISOString()}).eq('organization_id',org).eq('user_id',user.id).eq('calendar_profile_id',formText(form,'profile_id',40)||profile.id);if(error)throw error;return 'Phone subscription links revoked. Create a new link to reconnect.';});}
export async function syncCalendarNow(_:ActionState,form:FormData){return officeAction(async()=>{const {db,org,user}=await officeContext();const {data:c}=await db.from('calendar_connections').select('*').eq('organization_id',org).eq('user_id',user.id).eq('id',formText(form,'id',40)).maybeSingle();if(!c)throw new Error('Connection not found.');await syncGoogleCalendar(c);return 'Google Calendar is up to date.';});}
export async function disconnectGoogle(_:ActionState,form:FormData){return officeAction(async()=>{const {db,org,user}=await officeContext();const id=formText(form,'id',40);const {data:c}=await db.from('calendar_connections').select('*').eq('organization_id',org).eq('user_id',user.id).eq('id',id).maybeSingle();if(!c)throw new Error('Connection not found.');try{await googleRequest(`/calendars/${encodeURIComponent(c.google_calendar_id)}`,await googleAccessToken(c.refresh_token),'DELETE');}catch{/* The user can still disconnect after revoking Google access. */}const {error}=await db.from('calendar_connections').delete().eq('id',id).eq('user_id',user.id);if(error)throw error;await recordOfficeAction(org,user.id,'calendar.google_disconnected','calendar_connections',id);return 'Disconnected. If Google access had already expired, remove the old church calendar in Google Calendar manually.';});}
