import Link from "next/link";
import { getCurrentProfile,getUserPermissions } from "@/lib/auth/session";
import { createServiceRoleClient } from "@/lib/supabase/server";
import { googleConfig } from "@/lib/calendar/integrations";
import { OfficeActionForm } from "@/components/office-action-form";
import { syncCalendarNow,disconnectGoogle } from "./actions";
import { PhoneSubscription } from "./phone-subscription";
import { SITE_URL } from "@/lib/org";
export default async function CalendarPage({searchParams}:{searchParams:Promise<{error?:string;connected?:string}>}){
 const profile=await getCurrentProfile();if(!profile?.auth_user_id)return null;const params=await searchParams;const permissions=await getUserPermissions(profile.organization_id);const db=createServiceRoleClient();const [{data:connections},{data:pastor},config]=await Promise.all([db.from('calendar_connections').select('id,calendar_profile_id,google_email,last_synced_at,last_error').throwOnError().eq('user_id',profile.auth_user_id).eq('organization_id',profile.organization_id),permissions.has('calendar.share')?db.from('pastoral_team_members').select('profile_id').throwOnError().eq('organization_id',profile.organization_id).eq('is_active',true).eq('is_pastor',true).order('sort_order').limit(1).maybeSingle():Promise.resolve({data:null}),googleConfig()]);const calendars=[{id:profile.id,title:'My church calendar',description:'Your own appointments and working hours.'},...(pastor&&pastor.profile_id!==profile.id?[{id:pastor.profile_id,title:'Pastor’s calendar',description:'Shared with the Pastor and Administrative Team. Manage working hours and appointments in the church platform.'}]:[])];
 return <><div className="dashboard-header"><div><h1>Calendar connections</h1><p>Choose the Google account or phone calendar where you want your church schedule.</p></div></div>{params.error&&<p className="office-card" role="alert">{params.error==='google_not_configured'?'The Super Administrator needs to configure Google Calendar first.':params.error.slice(0,250)}</p>}{params.connected&&<p role="status">Your selected Google account is connected.</p>}{calendars.map(c=>{const connection=connections?.find(x=>x.calendar_profile_id===c.id);return <section className="panel" key={c.id}><h2>{c.title}</h2><p>{c.description}</p>{connection?<><p><strong>Connected to {connection.google_email}</strong></p><p className="form-note">Last synced: {connection.last_synced_at?new Date(connection.last_synced_at).toLocaleString('en-JM',{timeZone:'America/Jamaica'}):'Not yet synced'}</p>{connection.last_error&&<p role="alert">{connection.last_error}</p>}<div className="office-toolbar"><OfficeActionForm action={syncCalendarNow} label="Sync now"><input type="hidden" name="id" value={connection.id}/></OfficeActionForm><OfficeActionForm action={disconnectGoogle} label="Disconnect & remove church calendar"><input type="hidden" name="id" value={connection.id}/></OfficeActionForm></div></>:config.clientId&&config.clientSecret?<a className="primary-button" href={`/api/calendar/google/connect?profile=${c.id}`}>Choose Google account & connect</a>:<p className="form-note">Google Calendar account connection is awaiting setup.{permissions.has('integrations.manage')&&<> <Link href="/admin/integrations">Configure Google Calendar</Link></>}</p>}<p className="form-note">Updates are sent from the church platform to Google. Make calendar changes here so availability and booking checks stay accurate.</p><PhoneSubscription profileId={c.id}/></section>;})}<section className="panel"><h2>Public church events</h2><p>Subscribe to published church events using your calendar app’s “Add calendar from URL” option.</p><label>Church events URL<input readOnly value={`${SITE_URL}/calendar.ics`}/></label><a className="secondary-button" href={`${SITE_URL.replace(/^https?:/,'webcal:')}/calendar.ics`}>Open in phone calendar</a></section></>;
}
