import Link from "next/link";
import { notFound } from "next/navigation";
import { getOrganizationId,getUserPermissions } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { AccessDenied } from "@/components/access-denied";
import { OfficeActionForm } from "@/components/office-action-form";
import { fieldLabel } from "@/lib/documents/design";
import { saveMember,deleteMember } from "./actions";
export default async function MemberRecord({params}:{params:Promise<{id:string}>}){const {id}=await params;const org=await getOrganizationId();const permissions=await getUserPermissions(org??"");if(!permissions.has("people.read"))return <AccessDenied/>;const db=await createClient();const {data:p}=await db.from("profiles").select("*").throwOnError().eq("organization_id",org??"").eq("id",id).maybeSingle();if(!p)notFound();const fields=['first_name','last_name','email','phone','date_of_birth','gender','address_line1','city','parish','marital_status','occupation','employer','job_title','emergency_contact_name','emergency_contact_phone','joined_at','notes'] as const;return <><div className="dashboard-header"><div><p className="section-kicker">Member record</p><h1>{p.first_name} {p.last_name}</h1><span className="badge blue">{p.membership_status.replaceAll('_',' ')}</span></div><a className="secondary-button" href={`/api/office/people/${id}/file`}>Download member file (PDF)</a></div><div className="panel">{permissions.has("people.write")?<OfficeActionForm action={saveMember.bind(null,id)} label="Save member record"><div className="office-grid">{fields.map(k=><label key={k}>{fieldLabel(k)}{k==='notes'?<textarea name={k} defaultValue={p[k]??""} rows={5}/>:<input name={k} defaultValue={p[k]??""} type={k==='email'?'email':['date_of_birth','joined_at'].includes(k)?'date':'text'}/>}</label>)}</div></OfficeActionForm>:<dl>{fields.map(k=><div className="office-card" key={k}><dt><strong>{fieldLabel(k)}</strong></dt><dd style={{whiteSpace:'pre-wrap'}}>{p[k]||'—'}</dd></div>)}</dl>}</div>{permissions.has("people.delete")&&<details className="panel"><summary>Delete member record</summary><p>This removes the member record and disables sign-in. Historical church transactions remain. Staff accounts and your own account are protected.</p><OfficeActionForm action={deleteMember.bind(null,id)} label="Delete member"><label>Type DELETE to confirm<input name="confirmation" required autoComplete="off"/></label></OfficeActionForm></details>}<Link href="/admin/people">Back to directory</Link></>;}
