"use client";
import { useState } from "react";
import type { FormField } from "@/lib/office/forms";
import { OfficeActionForm } from "@/components/office-action-form";
import { saveOfficeForm } from "./actions";
export function FormBuilder({id,title="",description="",initialFields=[]}:{id?:string;title?:string;description?:string;initialFields?:FormField[]}) {
 const [fields,setFields]=useState<FormField[]>(initialFields);
 function edit(index:number,patch:Partial<FormField>){setFields(fields.map((f,i)=>i===index?{...f,...patch}:f));}
 return <OfficeActionForm action={saveOfficeForm} label={id?"Save form changes":"Save new form"}><input type="hidden" name="id" value={id??""}/><input type="hidden" name="fields" value={JSON.stringify(fields)}/><label>Form title<input name="title" required defaultValue={title}/></label><label>Introduction<textarea name="description" defaultValue={description}/></label>{fields.map((field,index)=><div key={field.id} className="office-form-field"><div className="form-row"><label>Question<input value={field.label} required onChange={e=>edit(index,{label:e.target.value})}/></label><label>Answer type<select value={field.type} onChange={e=>edit(index,{type:e.target.value as FormField["type"]})}>{["text","textarea","email","date","number","select","checkbox"].map(t=><option key={t} value={t}>{t==="textarea"?"Long answer":t==="select"?"Dropdown":t}</option>)}</select></label></div>{field.type==="select"&&<label>Choices (one per line)<textarea value={(field.options??[]).join("\n")} onChange={e=>edit(index,{options:e.target.value.split("\n")})}/></label>}<label><input type="checkbox" checked={field.required} onChange={e=>edit(index,{required:e.target.checked})}/> Required</label><div className="button-row"><button type="button" className="secondary-button compact" disabled={index===0} onClick={()=>{const next=[...fields];[next[index-1],next[index]]=[next[index]!,next[index-1]!];setFields(next);}}>Move up</button><button type="button" className="link-button" onClick={()=>setFields(fields.filter((_,i)=>i!==index))}>Remove field</button></div></div>)}<button type="button" className="secondary-button" onClick={()=>setFields([...fields,{id:`field_${crypto.randomUUID().replaceAll('-','').slice(0,12)}`,label:"",type:"text",required:false}])}>+ Add a question</button><p className="form-note">The church logo, navy heading, and gold accents are added automatically.</p></OfficeActionForm>;
}
