import { getOrganizationId,getUserPermissions } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { AccessDenied } from "@/components/access-denied";
import { OfficeActionForm } from "@/components/office-action-form";
import { FormBuilder } from "./form-builder";
import { sendOfficeForm } from "./actions";
import type { FormField } from "@/lib/office/forms";
export default async function FormsPage(){
 const org=await getOrganizationId();if(!org||!(await getUserPermissions(org)).has("forms.manage"))return <AccessDenied/>;
 const db=await createClient();const [{data:forms,error},{data:people},{data:responses}]=await Promise.all([db.from("office_forms").select("*").throwOnError().eq("organization_id",org).order("created_at",{ascending:false}),db.from("profiles").select("id,first_name,last_name,email").throwOnError().eq("organization_id",org).order("last_name"),db.from("form_assignments").select("id,form_id,recipient_profile_id,form_snapshot,answers,submitted_at,expires_at,created_at").throwOnError().eq("organization_id",org).order("created_at",{ascending:false}).limit(100)]);
 return <><div className="dashboard-header"><div><p className="section-kicker">Administrative team</p><h1>Forms & responses</h1><p>Create branded forms, send private invitations, and review submitted information.</p></div></div>{error&&<p role="alert">Forms could not be loaded.</p>}<details className="panel"><summary><strong>Create a form</strong></summary><FormBuilder/></details><div className="office-grid">{forms?.map(f=><div className="panel" key={f.id}><h2>{f.title}</h2><p>{f.description}</p><details><summary>Edit questions</summary><FormBuilder id={f.id} title={f.title} description={f.description} initialFields={f.fields as FormField[]}/></details><OfficeActionForm action={sendOfficeForm} label="Email form invitation"><input type="hidden" name="form_id" value={f.id}/><label>Send to a member<select name="recipient_id" required><option value="">Choose a member</option>{people?.filter(p=>p.email).map(p=><option key={p.id} value={p.id}>{p.first_name} {p.last_name} — {p.email}</option>)}</select></label></OfficeActionForm></div>)}</div><div className="panel"><h2>Invitations & submitted forms</h2>{!responses?.length&&<p className="panel-empty">Sent invitations and responses will appear here.</p>}{responses?.map(r=>{const person=people?.find(p=>p.id===r.recipient_profile_id);const snap=r.form_snapshot as {title:string;fields:FormField[]};const answers=r.answers as Record<string,string>|null;return <details key={r.id} className="office-card"><summary><strong>{snap.title}</strong> · {person?.first_name} {person?.last_name} · {r.submitted_at?"Submitted":new Date(r.expires_at)<new Date()?"Expired":"Awaiting response"}</summary>{answers&&<dl>{snap.fields.map(f=><div key={f.id}><dt><strong>{f.label}</strong></dt><dd style={{whiteSpace:"pre-wrap"}}>{answers[f.id]||"—"}</dd></div>)}</dl>}</details>;})}</div></>;
}
